FEAT: Now you can sprint, i guess
ss220club/Skyrat-tg pull request #48
Opened 2023-05-07 19:07 UTC by ImJustKisik

Добавил возможность систему спринта, использующую родной стат стамины. 
Что мы получим: 
- В основном все будут ходить пешком, а не носиться по коридорам на манер школьников.
- Если нужно быстро куда-то бежать, то бег все еще остается лучшим вариантом.
- Бегать 24 часа в сутки 7 дней в неделю - не получится, после пробежки усталость даёт о себе знать.
- Решение о том, быстро или нет идти куда-то, дает вам некоторые преимущества. 
 Например: Необходимость учитывать, хотите ли вы не тратить выносливость, когда бежите на задержание преступника.

Дополнительные вещи (возможно, вероятно?), будут(?) добавлены позже;

- [ ] Бег в скафандре - расходует стамину больше, чем бег без него. 
- [ ] Квирк, позволяющий иметь больше выносливости, но (cильно?) повышающий голод.
- [ ] Бонус к выносливости для определенных профессий? (карготехи, парамедики)
- [ ] У толстых персонажей меньше выносливости?

<summary>Чейнджлог: </summary>

🆑
add: Бег теперь будет расходовать выносливость. Расход можно настроить в конфигурации. Если у вас закончится выносливость, вы не сможете бежать снова, пока она не пополнится.
add: Теперь вы можете удерживать shift для спринта и отпускать его для ходьбы.
/🆑

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-05-07 19:16 UTC, larentoun commented on modular_ss220/modules/sprint/sprint.dm
> +	update_stamina_hud()
Это убери, будет пофикшено на апстриме

2023-05-07 19:19 UTC, dj-34 commented
сделай readme.md в папке с модулем с темплейта modular_skyrat/module.template.md
перечисли файлы которые изменил, чтоб проще потом было находить если че

2023-05-07 19:19 UTC, larentoun commented on code/datums/keybinding/mob.dm
> +	user.setmovingslowly()
зачем делать верб, если можно вызвать это у `user.mob` и не плодить лишнего?

2023-05-07 19:20 UTC, larentoun commented on code/datums/keybinding/mob.dm
> +	user.setmovingquickly()
зачем делать верб, если можно вызвать это у user.mob и не плодить лишнего?

2023-05-07 19:20 UTC, larentoun commented on code/datums/keybinding/mob.dm
> +/datum/keybinding/mob/move_quickly
гостам не нужен спринт, переведи в `living`

2023-05-07 19:21 UTC, larentoun commented on code/modules/mob/mob_movement.dm
> +	//SS220 ADDITION START: STAMINA SYSTEM
Почему оно на клиенте, а не на ливинг мобе?

2023-05-07 19:22 UTC, larentoun commented on modular_ss220/modules/sprint/sprint.dm
> +/datum/config_entry/flag/enable_sprint
неявно дефоултное значение

2023-05-07 19:23 UTC, larentoun commented on modular_ss220/modules/sprint/sprint.dm
> +	return cost
можно было бы сразу возвращать значение с конфига

2023-05-08 08:18 UTC, ImJustKisik commented on code/datums/keybinding/mob.dm
> +/datum/keybinding/mob/move_quickly
Погляди в начало файла, это просто сортировка по категориям

2023-05-08 09:11 UTC, lebedev requested changes

2023-05-08 09:11 UTC, lebedev commented on code/modules/mob/mob_movement.dm
>  /mob/proc/toggle_move_intent(mob/user)
Почему не оверрайдом прока?

2023-05-08 09:11 UTC, lebedev commented on code/modules/mob/mob_movement.dm
> +	mob.hadle_sprint(L) //SS220 SPRINT
`hadle` -- опечатка

2023-05-08 09:11 UTC, lebedev commented on modular_ss220/modules/sprint/sprint.dm
> +			if(prob(10) && iscarbon(affected))
Условия не объединены, вложенность кода субоптимальна.

2023-05-08 09:11 UTC, lebedev commented on modular_ss220/modules/sprint/sprint.dm
> +		to_chat(src, span_warning("You are unable run because you're exhausted"))
unable TO run?

2023-05-08 09:11 UTC, lebedev commented on modular_ss220/modules/sprint/sprint.dm
> +		if (HAS_TRAIT(src,TRAIT_NORUNNING))
Пробел после запятой, лишний пробел после ифа.

2023-05-08 09:11 UTC, lebedev commented on modular_ss220/modules/sprint/sprint.dm
> +			selector.update_appearance()
```suggestion
	for(var/atom/movable/screen/mov_intent/selector in hud_used?.static_inventory)
		selector.update_appearance()
```
Почему не так?

2023-05-08 09:12 UTC, lebedev commented on code/datums/keybinding/mob.dm
> +	return TRUE
Избыточно

2023-05-08 09:14 UTC, lebedev commented on code/modules/mob/mob_movement.dm
> +			to_chat(src, span_warning("You are unable to run because you're exhausted"))
Так `src` или `user`? Понамешано

2023-05-08 10:48 UTC, ImJustKisik commented on modular_ss220/modules/sprint/sprint.dm
> +			if(prob(10) && iscarbon(affected))
ну, вроде бы исправил

2023-05-08 10:48 UTC, ImJustKisik commented on code/modules/mob/mob_movement.dm
>  /mob/proc/toggle_move_intent(mob/user)
сдеал оверрайдом

2023-05-15 15:31 UTC, TrashDoxx commented
Хочу, чтоб ебало ломалось при спринте в стену.
Как в одной чудесной билдуле.

2023-05-15 17:02 UTC, TrashDoxx commented
> > Хочу, чтоб ебало ломалось при спринте в стену. Как в одной чудесной билдуле.
> 
> это же тот билд где свинок пюрешат?

Я никогда не пюрешил свинок, это подделка.

2023-05-21 11:41 UTC, closed without merging