Turn blue security to red again
ss220club/Skyrat-tg pull request #49
Opened 2023-05-07 20:54 UTC by dj-34

## About The Pull Request
Возвращает синее СБ в красное.
Я не уверен что смогу это завершить, там насрано...

## How This Contributes To The Skyrat Roleplay Experience

Nice

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: Red security
/:cl:

2023-05-07 21:27 UTC, lebedev requested changes

2023-05-07 21:27 UTC, lebedev commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
Не используется. Давай удалим.

2023-05-07 21:27 UTC, lebedev commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/datum/outfit/job/security
Давай оставим только те поля, которые оверрайдятся. Поля, которые не меняются, дублировать не нужно.

2023-05-07 21:27 UTC, lebedev commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +	suit = /obj/item/clothing/suit/armor/vest/warden //SKYRAT EDIT CHANGE - Original: /obj/item/clothing/suit/armor/vest/warden/alt
Здесь либо можно оверрайдом выдать старую вещь, либо оверрайднуть саму вещь. В двух местах сразу делать не нужно.

2023-05-07 21:27 UTC, lebedev commented on modular_ss220/modules/redsec/code/clothes_bluesec.dm
> +/obj/item/clothing/under/plasmaman/security/bluesec
Не используется?

2023-05-07 21:39 UTC, dj-34 commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
Я хочу оставить для щитспавнов/ЦК

2023-05-07 21:45 UTC, lebedev commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
Это не нужно, давай грохнем.

2023-05-07 21:50 UTC, dj-34 commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
> Это не нужно, давай грохнем.

Та всмысле не нужно? У нас тогда просто так спрайты валяться будут

2023-05-07 21:51 UTC, larentoun commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
Нужно оставлять, потому что еще не ясно, что будет с мейнами. Может там будет блусэк

2023-05-07 21:52 UTC, dj-34 commented on modular_ss220/modules/redsec/code/blue_to_red_security.dm
> +/obj/machinery/vending/wardrobe/sec_wardrobe/bluesec
Я вообще считаю что тем чем я ща занимаюсь, это пустая трата времени kekwat. Поэтому вы этому ПРу не уделяйте много времени

2023-05-10 23:56 UTC, Aylong220 commented
Ты обязательно выживешь :pepeKotya:

2023-05-23 02:28 UTC, dj-34 commented
хилимся живём, ПР готов

2023-05-23 18:59 UTC, Furrior approved these changes

2023-05-23 18:59 UTC, merged