Feat: Bar signs from padarise.
ss220club/Skyrat-tg pull request #79
Opened 2023-05-12 22:38 UTC by Aylong220

## Описание изменений

Добавил барные вывески с пары,
Все вывески перенесены в модуль, так что можно спокойно добавлять новые.

## Демонстрация изменений

![image](https://github.com/ss220club/Skyrat-tg/assets/69762909/a4d8ef2e-eb3e-449f-a77a-848677702451)

2023-05-15 05:29 UTC, Vallat requested changes
Ты исключаешь основной файл и файлы скайрата, что делать категорически нельзя, так как это может вылиться в мерж-конфликты.

2023-05-15 07:48 UTC, Aylong220 commented
> Ты исключаешь основной файл и файлы скайрата, а так же дублируешь уже написанный код повторно у нас, что делать категорически нельзя, так как это может вылиться в мерж-конфликты и другие проблемы в будущем.

Либо так, либо сделать как скайрату и просто поменять путь к иконкам в основном файле. Да и каким образом может быть конфликт, если ни файлы скайрата, ни основные не были задеты, а всего лишь отключены

2023-05-19 05:36 UTC, Vallat requested changes

2023-05-19 05:36 UTC, Vallat commented on code/game/machinery/barsigns.dm
> +	icon = 'modular_ss220/modules/barsigns/icons/barsigns.dmi' //SS220 EDIT CHANGE - ORIGINAL: modular_skyrat/modules/barsigns/icons/barsigns.dmi
Зачем ты меняешь это здесь, а не переписываешь **конкретно эту переменную** в нашем модуле?

2023-05-19 10:44 UTC, Aylong220 commented on code/game/machinery/barsigns.dm
> +	icon = 'modular_ss220/modules/barsigns/icons/barsigns.dmi' //SS220 EDIT CHANGE - ORIGINAL: modular_skyrat/modules/barsigns/icons/barsigns.dmi
Я не думал что это сработает, в прошлый раз не получалось, видать что-то не так делал

2023-05-19 10:45 UTC, Aylong220 commented on code/game/machinery/barsigns.dm
> +	icon = 'modular_ss220/modules/barsigns/icons/barsigns.dmi' //SS220 EDIT CHANGE - ORIGINAL: modular_skyrat/modules/barsigns/icons/barsigns.dmi
Не понимаю, почему тогда скайраты так не сделали

2023-05-19 10:55 UTC, Vallat approved these changes

2023-05-19 10:55 UTC, merged