feat: add traitor objectives translation
ss220club/Skyrat-tg pull request #83
Opened 2023-05-13 17:07 UTC by Gaxeer

feat: adds translation for all secondary traitor objectives

2023-05-13 20:19 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/final_objective/battlecruiser.dm
> +		станции на ближайщий крейсер. Возможно, вы захотите сообщить о своей принадлежности Синдикату \
```suggestion
		станции на ближайший крейсер. Возможно, вы захотите сообщить о своей принадлежности Синдикату \
```

2023-05-13 20:28 UTC, larentoun requested changes
Мелкие правки грамматики, а также добавь пустую строку в конце файлов. VSCode вообще должен автоматически его добавлять, а тут его нет :xmm:

2023-05-13 20:28 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/final_objective/battlecruiser.dm
> +		станции на ближайщий крейсер. Возможно, вы захотите сообщить о своей принадлежности Синдикату \
```suggestion
		станции на ближайший крейсер. Возможно, вы захотите сообщить о своей принадлежности Синдикату \
```

2023-05-13 20:28 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/final_objective/objective_dark_matteor.dm
> +		После того, как спутники будут откалиброваны, сингулярность появится. \
```suggestion
		После того как спутники будут откалиброваны, сингулярность появится. \
```

2023-05-13 20:28 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/final_objective/romerol.dm
> +	description = "Отправляйтесь в %AREA% и получите эксперементальное биологическое оружие. \
```suggestion
	description = "Отправляйтесь в %AREA% и получите экспериментальное биологическое оружие. \
```

2023-05-13 20:28 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/hack_comm_console.dm
> +	name = "Взломайте коммуникационную консоль чтобы призвать на станцию неизвестную угрозу."
```suggestion
	name = "Взломайте коммуникационную консоль, чтобы призвать на станцию неизвестную угрозу."
```

2023-05-13 20:28 UTC, larentoun commented on modular_ss220/modules/translations/master_files/code/modules/antagonists/traitor/objectives/steal.dm
> +		тогда дополнительное вознаграждание составит: репутации - %PROGRESSION%, телекристаллов - %TC%."
```suggestion
		тогда дополнительное вознаграждение составит: репутации - %PROGRESSION%, телекристаллов - %TC%."
```

2023-05-21 11:52 UTC, larentoun commented
@Gaxeer приди, порядок наведи!

2023-05-29 05:46 UTC, PhantornRU commented
@Gaxeer приди, порядок наведи!

2023-05-29 18:15 UTC, Gaxeer commented
Порядок будет наведен в другом месте ratge

2023-05-29 18:15 UTC, closed without merging